/** Model-facing contracts for the tools registered by this module. */
import type { ToolContract } from "../runtime/tool-contract.ts";
import { SWARM_BASH_DESCRIPTION } from "./swarm-bash.ts";

export const HEADLESS_BASH_CONTRACT: ToolContract = {
  description: SWARM_BASH_DESCRIPTION,
  parameters: {"properties":{"command":{"description":"Shell command to execute","type":"string"},"cwd":{"description":"Working directory (use this instead of 'cd')","type":"string"},"description":{"description":"Brief label for this command shown in the status header and TUI (5-10 words)","type":"string"},"env":{"additionalProperties":{"type":"string"},"description":"Extra environment variables to set","properties":{},"type":"object"},"timeout_seconds":{"default":90,"description":"Max seconds to wait as an integer number (never boolean); values below 60 are raised automatically","type":"integer"}},"required":["command"],"type":"object"},
};

export const INTERACTIVE_BASH_CONTRACT: ToolContract = {
  description: "Execute shell commands and return the output. Supports pipes, redirections, and shell features.\nBoth stdout and stderr are captured.\n\nIMPORTANT: Pass timeout_seconds as a JSON integer number (never boolean true, and do not use a timeout field). Example: timeout_seconds=90. You MUST set it for every command to prevent hanging.\n\nCommand runs and blocks until completion or timeout.\n- If completes within timeout: Returns output immediately\n- If exceeds timeout: Auto-backgrounds and returns task_id for later retrieval\n\nParameters:\n- command (required): Shell command to execute\n- cwd: Working directory (default: current directory)\n- env: Environment variables as key-value pairs\n- timeout_seconds (REQUIRED): Maximum seconds to wait before auto-backgrounding\n\nExample:\n{\n  \"command\": \"npm test\",\n  \"timeout_seconds\": 30\n}\nReturns: Output if completes in 30s, or {\"backgrounded\": true, \"task_id\": \"...\"} if exceeds timeout",
  parameters: {"properties":{"background":{"description":"Return immediately and run the command in the background","type":"boolean"},"command":{"description":"Shell command to execute","type":"string"},"cwd":{"description":"Working directory (use this instead of 'cd')","type":"string"},"description":{"description":"Brief label for this command shown in the status header and TUI (5-10 words)","type":"string"},"env":{"additionalProperties":{"type":"string"},"description":"Extra environment variables to set","properties":{},"type":"object"},"timeout_seconds":{"default":90,"description":"REQUIRED: Integer seconds as a JSON number, e.g. 90 (booleans are invalid). Auto-backgrounds if exceeded. Minimum: 1 second.","minimum":1,"type":"integer"}},"required":["command","timeout_seconds"],"type":"object"},
};

export const READBACKGROUNDCOMMAND_CONTRACT: ToolContract = {
  description: "Reads output and status from a background bash command.\n\nUse this tool to:\n- Check the status of a background process (running, completed, failed, cancelled)\n- Read the stdout/stderr output from the process\n- Get the exit code when the process has completed\n- Query specific lines or search output with a pattern\n\nThe output is returned as structured JSON with metadata including timestamps,\nline numbers, and stream type (stdout/stderr) for each line.\n\nHeartbeat fields on metadata tell you whether a long-running process is still\nmaking progress without needing to diff polls yourself:\n- \"last_output_at\": RFC3339 timestamp of the most recent line written.\n- \"seconds_since_last_output\": how long ago that was (0 if never output).\n- \"bytes_written\": cumulative output size in bytes (strictly non-decreasing).\nA process that is \"running\" but has a high seconds_since_last_output may still\nbe healthy (network I/O, LLM calls) — prefer another poll over a cancel unless\nthe gap exceeds several minutes OR bytes_written has not changed between polls.\n\nIMPORTANT: By default only the last 100 lines (tail) are returned in the \"output\"\narray to keep responses concise. When the output is truncated, \"metadata.output_file\"\ncontains the path to a temp file with the complete output — read that file with the\nRead or Bash tool if you need earlier lines.\n\nParameters:\n- task_id (required): The ID of the background process to read from\n- action: \"output\" (default), \"status\", \"cancel\", or \"list\"\n- from_line: Start reading from this line number (1-indexed, default: 1)\n- max_lines: Maximum number of lines to return (default: 100, capped at 1000)\n- pattern: Regex pattern to filter output lines (optional)\n- stream: Filter by stream type - \"stdout\", \"stderr\", or empty for all (optional)",
  parameters: {"properties":{"action":{"default":"output","description":"Action to perform: output (get output lines, default), status (get process state only), cancel (terminate process), list (list all background processes)","enum":["status","output","cancel","list"],"type":"string"},"from_line":{"default":1,"description":"Start reading from this line number (1-indexed)","type":"integer"},"max_lines":{"default":100,"description":"Maximum number of lines to return (default: 100 tail lines; capped at 1000). When truncated, see metadata.output_file for the full output.","type":"integer"},"pattern":{"description":"Regex pattern to filter output lines","type":"string"},"stream":{"description":"Filter by stream type (stdout, stderr, or empty for all)","enum":["stdout","stderr",""],"type":"string"},"task_id":{"description":"The ID of the background process (returned when command was backgrounded)","type":"string"}},"required":[],"type":"object"},
};

export const CONTRACTS: Record<string, ToolContract> = {
  bash: HEADLESS_BASH_CONTRACT,
  Bash: INTERACTIVE_BASH_CONTRACT,
  ReadBackgroundCommand: READBACKGROUNDCOMMAND_CONTRACT,
};
