/** Model-facing contracts for the tools registered by this module. */
import type { ToolContract } from "../runtime/tool-contract.ts";

export const WEBSEARCH_CONTRACT: ToolContract = {
  description: "Performs a web search and returns current, sourced results.\n\nSupports two backends:\n- Anthropic (default): powered by Claude's built-in web search via your Claude Code OAuth session.\n- Exa: powered by Exa's AI search API (set EXA_API_KEY environment variable or configure explicitly).\n\nUse this tool to:\n- Find current information, news, or recent events\n- Look up technical documentation, APIs, or library usage\n- Research topics that require up-to-date information\n- Verify facts or find authoritative sources\n\nFor coding agents, prefer the Exa backend which returns query-focused highlights (token-efficient,\nhigh groundedness per WebCode benchmarks) and supports deep search modes for niche/complex queries.\n\nYou can restrict results to specific domains with allowed_domains, or exclude domains with\nblocked_domains (mutually exclusive). The max_results parameter controls how many results\nare fetched (default 10, max 20).\n\nExample queries:\n- \"latest Go 1.22 features\"\n- \"Kubernetes deployment best practices 2024\"\n- \"current weather API providers\"",
  parameters: {"properties":{"allowed_domains":{"description":"Only include search results from these domains (e.g. [\"nytimes.com\",\"bbc.com\"]). Cannot be combined with blocked_domains.","items":{"type":"string"},"type":"array"},"blocked_domains":{"description":"Never include search results from these domains. Cannot be combined with allowed_domains.","items":{"type":"string"},"type":"array"},"category":{"description":"Filter results to a content category. Valid values: \"news\", \"company\", \"financial report\", \"research paper\", \"pdf\", \"personal site\", \"people\". Exa backend only.","enum":["news","company","financial report","research paper","pdf","personal site","people"],"type":"string"},"end_published_date":{"description":"Only return pages published before this date (ISO 8601). Exa backend only.","type":"string"},"exclude_text":{"description":"Text that must NOT appear in result pages (up to 1 phrase, max 5 words). Exa backend only.","items":{"type":"string"},"type":"array"},"include_text":{"description":"Text that must appear in result pages (up to 1 phrase, max 5 words). Pin results to a specific library name or version. Exa backend only.","items":{"type":"string"},"type":"array"},"max_results":{"default":10,"description":"Maximum number of results to return (default: 10, max: 20)","type":"integer"},"query":{"description":"The search query to execute. Be specific and descriptive for better results.","type":"string"},"start_published_date":{"description":"Only return pages published after this date (ISO 8601, e.g. \"2025-08-01T00:00:00.000Z\"). Useful for filtering to recent library releases or changelogs. Exa backend only.","type":"string"},"type":{"description":"Search mode (Exa backend only). \"auto\" (default) intelligently combines methods. \"neural\" uses embedding-based semantic search. \"fast\"/\"instant\" trade quality for lower latency. \"deep-lite\", \"deep\", \"deep-reasoning\", \"deep-max\" perform deep web research with synthesised output — use \"deep\" or \"deep-reasoning\" for niche coding questions, fresh SDK docs, or changelogs.","enum":["auto","fast","instant","deep-lite","deep","deep-reasoning"],"type":"string"}},"required":["query"],"type":"object"},
};

export const X_SEARCH_CONTRACT: ToolContract = {
  description: "Search X (Twitter) posts, threads, and profiles using xAI's native X Search.\n\nxAI has real-time, privileged access to all of X's data (Elon Musk owns both\ncompanies). This tool is fundamentally different from web scraping — Grok\nruns the search server-side with full fidelity to actual post content,\nengagement, and recency.\n\nUse this tool to:\n- Find recent tweets on any topic\n- Search specific users' posts (allowed_x_handles)\n- Research what's being said about a person, company, or event on X\n- Analyze media attached to posts (images, videos)\n- Filter by date range\n\nReturns the answer synthesized by Grok with direct citation links to posts.",
  parameters: {"properties":{"allowed_x_handles":{"description":"Only include posts from these X handles (max 10, without @). Mutually exclusive with excluded_x_handles.","items":{"type":"string"},"type":"array"},"enable_image_understanding":{"default":false,"description":"Whether to analyze images attached to X posts. Default false.","type":"boolean"},"enable_video_understanding":{"default":false,"description":"Whether to analyze videos attached to X posts. Default false.","type":"boolean"},"excluded_x_handles":{"description":"Exclude posts from these X handles (max 10, without @). Mutually exclusive with allowed_x_handles.","items":{"type":"string"},"type":"array"},"from_date":{"description":"Start date for results in YYYY-MM-DD format.","type":"string"},"query":{"description":"What to search for on X. Can be a topic, hashtag, question, or statement.","type":"string"},"to_date":{"description":"End date for results in YYYY-MM-DD format.","type":"string"}},"required":["query"],"type":"object"},
};

export const XAI_WEB_SEARCH_CONTRACT: ToolContract = {
  description: "Search the web in real-time using xAI's (Grok's) built-in web search.\n\nGrok browses the live web server-side — fetching pages, reading content, and\nsynthesizing an answer with source citations. Unlike static search engines,\nGrok can follow links and read full page content.\n\nOptionally filter to or exclude specific domains (max 5 each).\n\nReturns Grok's synthesized answer plus citation URLs. Use for current events,\ndocumentation, research — anything that benefits from live web access.",
  parameters: {"properties":{"allowed_domains":{"description":"Only include results from these domains (max 5, e.g. [\"github.com\"]). Mutually exclusive with excluded_domains.","items":{"type":"string"},"type":"array"},"excluded_domains":{"description":"Exclude results from these domains (max 5). Mutually exclusive with allowed_domains.","items":{"type":"string"},"type":"array"},"query":{"description":"What to search for.","type":"string"}},"required":["query"],"type":"object"},
};

export const CONTRACTS: Record<string, ToolContract> = {
  websearch: WEBSEARCH_CONTRACT,
  x_search: X_SEARCH_CONTRACT,
  xai_web_search: XAI_WEB_SEARCH_CONTRACT,
};
