import {it,expect,vi} from "vitest";import {mkdtempSync,readFileSync,rmSync} from "node:fs";import {join} from "node:path";import {tmpdir} from "node:os";
import {runMemoryMaintenance} from "../../lib/context/memory-maintenance-runner.ts";
it("forks a private active-branch snapshot, preserves IDs, and revokes its write lease",async()=>{const root=mkdtempSync(join(tmpdir(),"maintenance-runner-"));try{const branch=[{type:"message",id:"u",parentId:null,message:{role:"user",content:[{type:"text",text:"Use PostgreSQL"}]}},{type:"message",id:"a",parentId:"u",message:{role:"assistant",content:[{type:"thinking",thinking:"hidden"},{type:"text",text:"not proof"}]}}];const before=JSON.stringify(branch);const exec=vi.fn(async(_cmd:string,args:string[],options:any)=>{expect(args).toContain("--fork");expect(args).toContain("--no-extensions");expect(args).toContain("--no-tools");expect(options.timeout).toBe(90000);return{code:0};});const r=await runMemoryMaintenance({exec},{cwd:root,model:{provider:"test",id:"model"},sessionManager:{getBranch:()=>branch,getSessionFile:()=>"parent.jsonl"}},"finding",{signal:new AbortController().signal});const raw=readFileSync(r.snapshot,"utf8");expect(raw).not.toContain("hidden");const rows=raw.trim().split("\n").map(JSON.parse);expect(rows.find(r=>r.id==="a").message.usage.totalTokens).toBe(0);expect(raw).toContain('"id":"u"');expect(JSON.stringify(branch)).toBe(before);expect(readFileSync(join(r.snapshot,"../active"),"utf8")).toBe("revoked");}finally{rmSync(root,{recursive:true,force:true});}});
it("fork evidence omits secret-bearing vault calls/results and opaque details",async()=>{
 const root=mkdtempSync(join(tmpdir(),"vault-fork-test-"));try{
 const branch=[{type:"message",id:"u",message:{role:"user",content:"Review integration metadata"}},{type:"message",id:"c",message:{role:"assistant",content:[{type:"toolCall",id:"v",name:"vault_get",arguments:{id:"demo",secret:"ARG_SENTINEL"}}]}},{type:"message",id:"v",message:{role:"toolResult",toolName:"vault_get",toolCallId:"v",content:'{"secret":"VALUE_SENTINEL"}',details:{secret:"DETAIL_SENTINEL"}}}];
 const r=await runMemoryMaintenance({exec:async()=>({code:0})},{cwd:root,model:{provider:"test",id:"model"},sessionManager:{getBranch:()=>branch}},"Review only",{signal:new AbortController().signal});
 const raw=readFileSync(r.snapshot,"utf8");expect(raw).not.toContain("ARG_SENTINEL");expect(raw).not.toContain("VALUE_SENTINEL");expect(raw).not.toContain("DETAIL_SENTINEL");
 }finally{rmSync(root,{recursive:true,force:true});}
});
