import { registerSupervisorBudget } from "../../lib/context/supervisor-live-state.ts";
import { registerAutoSkills, type Config } from "../../../packages/context/autogenskills/src/index.ts";
import { fileURLToPath } from "node:url";
import { join, resolve } from "node:path";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import "../../lib/runtime/hook-state.ts";
import { getSwarmSkillRegistry } from "../../lib/context/swarm-skill-registry.ts";
import { withSwarmToolSurface } from "../../lib/runtime/swarm-tool-surface.ts";
import { registerBootstrapHandoff } from "../../lib/runtime/bootstrap-dispatch.ts";

/** Pi adapter for Swarm's stateful autogenerated-skills lifecycle. */
export interface AutoSkillsExtensionOptions extends Config {}

/** Project settings live under .pi/config/ alongside prompt-context.json. */
const settingsFile = (cwd: string) => join(resolve(cwd), ".pi", "config", "swarm-settings.json");
/** ${SWARM_SESSION_ID} substitution source for Skill invocations (skill_tool.go sessionIDGetter). */
// swarm-tui sdk_integration.go SessionIDGetter returns "" ("safe default"),
// so ${SWARM_SESSION_ID} always expands to the empty string in `swarm -p`.
const SWARM_TUI_SESSION_ID = "";
export function autogenMode(cwd: string): Config["mode"] {
  const env = process.env.SWARM_AUTOGEN_MODE as Config["mode"] | undefined;
  if (env && ["never", "manual", "auto"].includes(env)) return env;
  try {
    const value = JSON.parse(readFileSync(settingsFile(cwd), "utf8")).autogen;
    if (value === false || value === "off" || value === "never") return "never";
    if (value === "manual") return "manual";
    if (value === true || value === "on" || value === "auto") return "auto";
  } catch { /* absent settings use the Swarm default */ }
  return "auto";
}
function saveAutogenMode(cwd: string, mode: Config["mode"]): void {
  const path = settingsFile(cwd); mkdirSync(join(resolve(cwd), ".pi"), { recursive: true });
  let settings: any = {}; try { settings = JSON.parse(readFileSync(path, "utf8")); } catch {}
  settings.autogen = mode === "never" ? false : mode;
  writeFileSync(path, `${JSON.stringify(settings, null, 2)}\n`, "utf8");
}

export function registerAutoSkillsExtension(pi: any, options: AutoSkillsExtensionOptions = {}) {
  const child = process.env.SWARM_CURATOR_CHILD === "1";
  const extensionPath = fileURLToPath(import.meta.url);
  const configuredDir = options.dir ?? process.env.SWARM_AUTOGEN_DIR;
  const dir = configuredDir?.trim() || join(process.env.HOME ?? process.cwd(), ".swarm", "skills", "autogen");
  const cwd = resolve((pi.getCwd?.() as string | undefined) ?? process.cwd());
  const closed = options.closed ?? (process.env.SWARM_SKILLS_CLOSED === "1");
  const allowedNames = options.allowedNames ?? process.env.SWARM_SKILLS_ALLOWED?.split(",").map(s => s.trim()).filter(Boolean);
  const curatorRunner = options.curatorRunner ?? (!child && typeof pi.exec === "function"
    ? async (request: Parameters<NonNullable<Config["curatorRunner"]>>[0]) => {
      const result = await pi.exec("env", [
        `SWARM_AUTOGEN_MODE=manual`,
        `SWARM_SKILLS_CLOSED=${closed ? "1" : "0"}`,
        ...(allowedNames ? [`SWARM_SKILLS_ALLOWED=${allowedNames.join(",")}`] : []),
        `SWARM_AUTOGEN_DIR=${dir}`,
        `SWARM_AUTOGEN_PREVIEW=${request.preview ? "1" : "0"}`,
        "SWARM_AUTOGEN_REQUIRE_VIEW=1",
        "SWARM_AUTOGEN_ACCOUNTING_EXEMPT=1",
        "SWARM_CURATOR_CHILD=1",
        "pi",
        "--no-session",
        "--no-extensions",
        "--extension", extensionPath,
        "--no-skills",
        "--no-context-files",
        "--no-prompt-templates",
        "--tools", "SkillManage",
        "--mode", "text",
        "-p", request.prompt,
      ], { cwd, timeout: request.timeoutMs });
      if (result.code !== 0 || result.killed) {
        throw new Error(`curator child failed (${result.killed ? "timeout" : `exit ${result.code}`}): ${result.stderr.trim()}`);
      }
      return { output: result.stdout.trim() };
    }
    : undefined);
  const registrationPi = new Proxy(pi, { get(target, key) { if (key === "registerTool") return (tool: any) => { registerBootstrapHandoff(tool); target.registerTool(tool); }; const value = target[key]; return typeof value === "function" ? value.bind(target) : value; } });
  const manager = registerAutoSkills(registrationPi, {
    ...options,
    budgetWidget: undefined,
    // Model-visible budget blocks and skill-review nudges are emitted by the
    // Swarm builtin hook pipeline (.pi/lib/runtime/swarm-builtin-hooks.ts) in
    // HooksManager priority order; this manager keeps accounting + curation.
    modelContext: false,
    dir,
    previewOnly: options.previewOnly ?? process.env.SWARM_AUTOGEN_PREVIEW === "1",
    requireReadBeforeWrite: options.requireReadBeforeWrite ?? process.env.SWARM_AUTOGEN_REQUIRE_VIEW === "1",
    accountingExempt: options.accountingExempt ?? process.env.SWARM_AUTOGEN_ACCOUNTING_EXEMPT === "1",
    curatorRunner,
    afterRevisionMutation: name => getSwarmSkillRegistry(pi, { cwd, autogenDir: dir, closed, allowedNames, allowedSkills: allowedNames }).refreshSkill(name, dir),
    skillInvoker: (name, args) => {
      const skill = getSwarmSkillRegistry(pi, { cwd, autogenDir: dir, closed, allowedNames, allowedSkills: allowedNames }).invoke(name, args, SWARM_TUI_SESSION_ID);
      return { skill: skill.name, version: skill.source === "autogen" ? "autogen" : "external", path: skill.filePath, instructions: skill.instructions, text: skill.text };
    },
  });
  pi.on("session_start", (_event:unknown,ctx:any)=>registerSupervisorBudget(ctx,()=>manager.budgetStatus()));
  pi.on("session_switch", (_event:unknown,ctx:any)=>registerSupervisorBudget(ctx,()=>manager.budgetStatus()));
  return manager;
}

export default function autogenskillsExtension(pi: any) {
  // Swarm autogen is enabled by default, but remains isolated from Pi's
  // native skill ecosystem. Persisted project settings or the environment can
  // disable it without exposing generated skills to Pi discovery.
  const cwd = resolve(pi.getCwd?.() ?? process.cwd());
  const mode = autogenMode(cwd);
  pi.registerCommand?.("swarm-autogen", { description: "Show or change Swarm autogenerated-skills mode (on, off, manual, status)", handler: async (args: string, ctx: any) => {
    const value = args.trim().toLowerCase();
    if (value === "status" || !value) { ctx.ui?.notify?.(`Swarm autogen: ${mode} (default: auto; applies on next session)`, "info"); return; }
    const next = value === "on" ? "auto" : value === "off" ? "never" : value;
    if (!["auto", "manual", "never"].includes(next)) { ctx.ui?.notify?.("Usage: /swarm-autogen on|off|manual|status", "warning"); return; }
    saveAutogenMode(cwd, next as Config["mode"]);
    ctx.ui?.notify?.(`Swarm autogen set to ${next}; restart or reload the session to apply.`, "info");
  }});
  if (mode === "never") return;
  registerAutoSkillsExtension(withSwarmToolSurface(pi), { mode, dir: process.env.SWARM_AUTOGEN_DIR || undefined });
  // Prompt composition is owned by swarm-prompt.ts. Autogen contributes
  // lifecycle nudges only when enabled by settings or environment.
}
